# Generated by Django 5.1.1 on 2024-09-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidoMaterno',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidoPaterno',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombreCuenta',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
